name: Update Codeberg mirror

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: 'https://codeberg.org/viresh-ratnakar/pages.git'
        REMOTE_NAME: 'codeberg'
        GIT_USERNAME: viresh-ratnakar
        GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}
